### ISSUE TITLE
Request: Ability to resize images on import

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#41]
I'm not sure I completely understand the format you are using for linking images yet however there is capability to set image sizes using something like:

![[Image.png|200]]

Where 200 could be a variable fed in via the Output Formatter?

**Comment by farling42** [comment]
Smart Images are imported to use the Leaflet plug-in, which adds support for map pins.

All other images are imported as separate asset files which are linked into their containing page using the simple obsidian format of:
![<filename>]

**Comment by farling42** [comment]
A specific height is set for Smart Images, since Leaflet requires a viewport onto the actual map; whilst currently no explicit height is given for other images.

**Comment by farling42** [comment]
A single number would define the width of the picture, so it would not widen when the page is widened.

**Comment by Sklore** [comment]
Smart Images are fine. An option for Simple Images would be great though. Personally I feel the images are taking up to much space. As a DM I want to review the picture quickly, maybe share it, but I need the content. I've been adding |200 to mine for example. 

![image](https://user-images.githubusercontent.com/8046697/145115864-88de646f-3ec9-459b-8a42-6bab698ebc2c.png)

**Comment by farling42** [comment]
V3.14 fixes this. Max Image Width field changes to numeric field, and now gets applied to markdown output.
