### ISSUE TITLE
Request: Preffix Suffix Tag Option

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#42]
An option to enable either a Preffix/Suffix as a tag would be fantastic. Perhaps as a on/off choice?
LWD required all Mechanics to have a suffix code to match the content. So this would be a great place to pull a tag from.

**Comment by farling42** [comment]
The output tool would require this to apply to ALL topics as they are imported.
Is this a feature that you'd prefer to apply differently to each topic?

**Comment by Sklore** [comment]
That's a good question. Could it be left as an optional choice? Then the user can decide. Personally I might do an export of only mechanics to bring in the tags for example.

**Comment by farling42** [comment]
Implemented in 3.14

**Comment by farling42** [comment]
Prefix implemented in 3.14; all tags will be put into the tag group called Prefix.
