### ISSUE TITLE
Feedback - Text Formatting

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#43]
Morning, 
Starting to really slow down and look at the output in detail. Not sure if there's anything that can be done about this. I've noticed over the years that the way text works in RW is rather odd (it cold also just be me, who knows) and it tends to add spaces in where they don't belong. This seems to be having an impacted on the output. 

Between paragraphs theres usually an empty line. If that line is clean, then the output format is fantastic. 
However in some situations there's spaces on the empty lines. Where that occurs the output format has a large gap between the paragraphs. 

Here's an example:
![image](https://user-images.githubusercontent.com/8046697/145269068-c2e68e91-0eb8-48a9-b42c-3e38b8e03a82.png)

And as you can see. The reason for the gap is there a spaces on the empty line. 
![image](https://user-images.githubusercontent.com/8046697/145269118-200d6ebe-f3f9-4f84-8113-4fee9a27ed53.png)

So yeah. Not sure if anything can be done. I see this as an issue with the source realm but FYI.

**Comment by farling42** [comment]
The removal of these extraneous spaces should be getting done in v 3.16. So that only a single line break.

**Comment by Sklore** [comment]
It's worked on some. Again though I think it's my data that's the issue. I have a heap of these. 

<br>
<space>
<br>

![image](https://user-images.githubusercontent.com/8046697/145644934-50b7fae6-d5f1-495b-af50-6e9a51d7b4fd.png)

![image](https://user-images.githubusercontent.com/8046697/145645108-2af7ccef-c207-477f-8246-3718da37b4b3.png)

**Comment by farling42** [comment]
RW seems to add some sort of non-standard space if you manually add a blank line between paragraphs in a single snippet.

It looks like the RWoutput tool removes some of them, but there is any formatting then the extra line isn't removed. 
e.g. if the whole snippet is set to italic, then internally in RW each paragraph is marked as italic, so the output tool doesn't notice that the "blank line paragraph" only has a space on it.

**Comment by Sklore** [comment]
Aren't you meant to be levelling ;)

**Comment by farling42** [comment]
I think I can remove blank paragraphs by simply checking for a paragraph consisting of only format symbols and white space.

I don't know if any people have added extra blank lines as intentional formatting - but markdown might mess with those anyway.

**Comment by farling42** [comment]
Have a look at the formatting improvements in 4.5 or later. I think it might improve this.

**Comment by Sklore** [comment]
Much better thanks!
