### ISSUE TITLE
Feedback - Heading Formatting

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#44]
I suspect this could be because the raw text is a whole paragraph of BOLD. 
![image](https://user-images.githubusercontent.com/8046697/145277921-cd9d83cd-52f0-45db-b6f5-0befae1fd25d.png)

Looks like the heading got confused about where it should start/end. 
![image](https://user-images.githubusercontent.com/8046697/145278006-f0086fb1-286c-4395-b83d-9299bd3aedf1.png)

Pattern seems to be where there is a line of BOLD is does weird things. 
![image](https://user-images.githubusercontent.com/8046697/145278263-fca0f2a6-8ff7-4c0b-b64f-d5b31bc9e21f.png)

![image](https://user-images.githubusercontent.com/8046697/145278291-102f64a0-d260-4da4-804c-50eacd07cf59.png)

Interestingly... that link does not exist in RW. I do wonder if it was linked once upon a time and I removed it though.

**Comment by farling42** [comment]
Could you see if version 3.15 fixes this issue. There have been some improvements to how the styles in multiple spans in the same paragraph are merged together.

**Comment by Sklore** [comment]
Heading is indeed fixed!

![image](https://user-images.githubusercontent.com/8046697/145489977-32bd443a-5df8-4c93-b1c2-ce6d0328b698.png)

Not sure what is happening up here though. 

![image](https://user-images.githubusercontent.com/8046697/145490026-cb689f58-bbb4-402c-9959-97d66569083c.png)

![image](https://user-images.githubusercontent.com/8046697/145490073-0c18f0ce-5a59-41ba-b706-d711532ef35a.png)

**Comment by farling42** [comment]
You might notice a lot of "<br/>" in your second image.

V3.16 reverses the change so that I will again be replacing "<br/>" with simple line breaks - it will remove all that horrible bold which isn't being properly cancelled.

**Comment by Sklore** [comment]
Back to normal :)

![image](https://user-images.githubusercontent.com/8046697/145555708-980d4001-13c6-40b9-9975-daf8b78e1735.png)
