### ISSUE TITLE
Request - MetaData For Tags

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#48]
Is it possible to get the tags added to the Meta Data?

Example: A spell is used by a Bard and it's an Transmutation Spell. 

```
---
ImportedOn: Sunday, 12 December 2021 9:55:01 PM
Tags: Category/Spell
Class: Bard
School: Transmutation 
parent:
  - 9. - Spell Descriptions
up:
  - 9. - Spell Descriptions
prev:
  - Zone of Truth
RWtopicId: Topic_425
---
```

This will enable the use of Dataview. For example: 

```
```dataview
table ImportedOn, Class, School
where (School = "Transmutation")
```
```

This then updates automatically to: 

![image](https://user-images.githubusercontent.com/8046697/145711048-06a3072b-5bb9-49d1-849e-f51d98c6448b.png)

This could be really powerful.

**Comment by farling42** [comment]
Does Dataview not work with Tags?

The note will contain a tag called School/Transmutation

**Comment by farling42** [comment]
In the code it can be done, but it would end with potentially A LOT of tags being listed in the metadata section. I don't know why dataview can't just find the tags in the main body of the note.

**Comment by farling42** [comment]
Would using "FROM #tag" generate the required list of topics? 

I gleaned it from reading https://blacksmithgu.github.io/obsidian-dataview/query/queries/

**Comment by farling42** [comment]
After a brief investigation of dataview, it seems to only work on fields in the frontmatter.

Although you can do "FROM #tag" to get all notes that have a particular tag (even if the tag isn't inside the frontmatter), from then on it can only pick fields within the frontmatter.
