### ISSUE TITLE
Tables - Acting Weird

### ISSUE THREAD

**Issue by Sklore** [farling42/RWoutput#55]
Hey mate, 
Tables seem to be doing something differently. 

Previous format: 
![image](https://user-images.githubusercontent.com/8046697/146695371-751ae114-23ad-4cff-8538-0480bbecb143.png)

Latest:
![image](https://user-images.githubusercontent.com/8046697/146695385-8477c71d-00d3-4700-beb1-926e03903f7b.png)

Also tables are getting stuck here, looks like the Heading for Ability Scores is getting in the way. 

## Other Details
**Ability Scores**: | **STR** | **DEX** | **CON** | **INT** | **WIS** | **CHA** |
|---|---|---|---|---|---|
| 18 (+4) | 18 (+4) | 18 (+4) | 17 (+3) | 20 (+5) | 20 (+5) |
 
![image](https://user-images.githubusercontent.com/8046697/146695393-1b4d4583-b726-4e39-9fee-bc38d7194069.png)

**Comment by farling42** [comment]
The change in the single attribute line is because of a change in the parsing that I made to detect some headers inside the HTML of HL portfolio files.

This should be simple to revert.

**Comment by farling42** [comment]
First problem should be fixed in 4.7 (when it gets released imminently).

**Comment by Sklore** [comment]
Much nicer. Thanks for that! Yell out if you want some test content btw. 
![image](https://user-images.githubusercontent.com/8046697/146749898-e38e02c1-6c9f-42a8-9ed7-1b9d3ee4f34a.png)

**Comment by farling42** [comment]
Second problem fixed in 4.10

Tables in Labeled_Text snippets weren't starting on their own line with a blank line between it and the title.
